- name: Variables on Play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: the url is = {{URL}}
# Note: if we declare a variable in Play level the all the tasks can access that variable

- name: Variables from File in Play level
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: the url is = {{URL}}



