- name: Demo Tags
  hosts: localhost
  tasks:
    - name: Centos
      debug:
        msg: Centos
      tags:
        - centos
    - name: Ubuntu
      debug:
        msg: Ubuntu
      tags:
        - ubuntu

## tags can be applicabled to play also
