- name: Setup Repo file for NodeJS
  ansible.builtin.copy:
    src: nodejs.repo
    dest: /etc/yum.repos.d/nodejs.repo

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop
    state: present

- name: Download App Code
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Clean Old App Code
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy App Code
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop

- name: Install Catalogue Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: Setup Catalogue SystemD Config File
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Start Catalogue Service
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes









